-- Insert roasters with expanded information
INSERT INTO roasters (
    id, name, description, location, website_url, logo_url, slug,
    coordinates, specialties, social_media, phone, email, instagram
)
VALUES 
(
    'e887d5d6-7b5a-4c74-9f37-7d5a5c5c5b5b',
    'Counter Culture Coffee',
    'A pioneer in sustainable, direct-trade coffee sourcing and education. Known for their commitment to quality, transparency, and environmental stewardship.',
    'Durham, NC',
    'https://counterculturecoffee.com',
    'https://counterculturecoffee.com/wp-content/themes/counter-culture/images/ccc-logo.svg',
    'counter-culture',
    '{"lat": 35.9940, "lng": -78.8986}',
    ARRAY['Single Origin', 'Direct Trade', 'Education'],
    '{"facebook": "counterculturecoffee", "instagram": "counterculturecoffee", "twitter": "counter_culture"}',
    '+1 (888) 238-5282',
    'info@counterculturecoffee.com',
    '@counterculturecoffee'
),
(
    'd887d5d6-7b5a-4c74-9f37-7d5a5c5c5b5a',
    'Intelligentsia Coffee',
    'Specialty coffee pioneers known for their direct trade practices and exceptional quality. Each coffee is carefully sourced and roasted to highlight its unique characteristics.',
    'Chicago, IL',
    'https://www.intelligentsiacoffee.com',
    'https://www.intelligentsiacoffee.com/media/logo/default/intelligentsia-logo.svg',
    'intelligentsia',
    '{"lat": 41.8781, "lng": -87.6298}',
    ARRAY['Direct Trade', 'Single Origin', 'Seasonal Blends'],
    '{"facebook": "intelligentsiacoffee", "instagram": "intelligentsiacoffee", "twitter": "intelligentsia"}',
    '+1 (888) 945-9786',
    'info@intelligentsiacoffee.com',
    '@intelligentsiacoffee'
),
(
    'f887d5d6-7b5a-4c74-9f37-7d5a5c5c5b5c',
    'Blue Bottle Coffee',
    'Artisanal coffee roaster focused on serving coffee at peak freshness. Every coffee is cupped, scored, and must meet strict quality standards.',
    'Oakland, CA',
    'https://bluebottlecoffee.com',
    'https://bluebottlecoffee.com/assets/blue-bottle-coffee-logo.svg',
    'blue-bottle',
    '{"lat": 37.8044, "lng": -122.2712}',
    ARRAY['Single Origin', 'Blends', 'Cold Brew'],
    '{"facebook": "bluebottlecoffee", "instagram": "bluebottlecoffee", "twitter": "bluebottleroast"}',
    '+1 (888) 252-2087',
    'info@bluebottlecoffee.com',
    '@bluebottlecoffee'
);

-- Insert beans with expanded information
INSERT INTO beans (
    id, name, slug, roaster_id, description, origin, roast_level, 
    process, tasting_notes, flavor_profile, price, weight, currency,
    altitude, variety, harvest, is_featured, image_url
)
VALUES 
(
    'a887d5d6-7b5a-4c74-9f37-7d5a5c5c5b5a',
    'Colombian Supremo',
    'counter-culture-colombian-supremo',
    'e887d5d6-7b5a-4c74-9f37-7d5a5c5c5b5b',
    'A classic Colombian coffee with notes of caramel, citrus, and milk chocolate. Well-balanced and medium-bodied.',
    'Colombia',
    'Medium',
    'Washed',
    ARRAY['Caramel', 'Citrus', 'Milk Chocolate'],
    '{"acidity": 3, "sweetness": 4, "body": 4}',
    19.00,
    340,
    'USD',
    '1500-1800m',
    'Castillo, Colombia',
    '2024',
    true,
    'https://images.unsplash.com/photo-1611854779393-1b2da9d400fe'
),
(
    'b887d5d6-7b5a-4c74-9f37-7d5a5c5c5b5b',
    'Ethiopian Yirgacheffe',
    'intelligentsia-ethiopian-yirgacheffe',
    'd887d5d6-7b5a-4c74-9f37-7d5a5c5c5b5a',
    'A bright and complex coffee with floral notes, bergamot, and honey sweetness.',
    'Ethiopia',
    'Light',
    'Washed',
    ARRAY['Jasmine', 'Bergamot', 'Honey'],
    '{"acidity": 4, "sweetness": 3, "body": 2}',
    21.00,
    340,
    'USD',
    '1800-2200m',
    'Heirloom',
    '2024',
    true,
    'https://images.unsplash.com/photo-1611854779393-1b2da9d400fe'
),
(
    'c887d5d6-7b5a-4c74-9f37-7d5a5c5c5b5c',
    'Bella Donovan Blend',
    'blue-bottle-bella-donovan-blend',
    'f887d5d6-7b5a-4c74-9f37-7d5a5c5c5b5c',
    'Our bestselling blend: a perfect introduction to craft coffee. Notes of chocolate, caramel, and molasses.',
    'Brazil, Ethiopia',
    'Medium-Dark',
    'Natural, Washed',
    ARRAY['Chocolate', 'Caramel', 'Molasses'],
    '{"acidity": 2, "sweetness": 4, "body": 5}',
    19.00,
    340,
    'USD',
    '1000-2000m',
    'Various',
    '2024',
    true,
    'https://images.unsplash.com/photo-1611854779393-1b2da9d400fe'
),
(
    'd887d5d6-7b5a-4c74-9f37-7d5a5c5c5b5d',
    'Kenya Karinga',
    'counter-culture-kenya-karinga',
    'e887d5d6-7b5a-4c74-9f37-7d5a5c5c5b5b',
    'A vibrant and juicy coffee with notes of blackberry, grapefruit, and brown sugar.',
    'Kenya',
    'Medium-Light',
    'Washed',
    ARRAY['Blackberry', 'Grapefruit', 'Brown Sugar'],
    '{"acidity": 5, "sweetness": 4, "body": 3}',
    23.00,
    340,
    'USD',
    '1700-1900m',
    'SL28, SL34',
    '2024',
    false,
    'https://images.unsplash.com/photo-1611854779393-1b2da9d400fe'
),
(
    'e887d5d6-7b5a-4c74-9f37-7d5a5c5c5b5e',
    'Guatemala Antigua',
    'intelligentsia-guatemala-antigua',
    'd887d5d6-7b5a-4c74-9f37-7d5a5c5c5b5a',
    'A smooth, full-bodied coffee with notes of chocolate, spice, and subtle fruit undertones.',
    'Guatemala',
    'Medium',
    'Washed',
    ARRAY['Chocolate', 'Spice', 'Orange'],
    '{"acidity": 3, "sweetness": 3, "body": 4}',
    20.00,
    340,
    'USD',
    '1500-1700m',
    'Bourbon, Caturra',
    '2024',
    false,
    'https://images.unsplash.com/photo-1611854779393-1b2da9d400fe'
);
